### Use this file to:
### 1) Set how far back you want to collect CVEs (in hours).
### 2) Set the minimum CVSS score will create a log entry.

# 1) Set how far back you want to collect CVEs (in hours).
# Format as an integer or float value.
timeDelta: 2

# 2) Set the minimum CVSS score will create a log entry.
# Format as an integer or float value with a single decimal place.
alertScore: 9.0
